#!/bin/sh
# ~/.config/bspwm/bspwmrc
# bspwm configuration (appearance, rules, gaps)

# ===== Monitor setup =====
source ~/.config/bspwm/monitor_setup.sh

# ===== Window appearance =====
bspc config border_width        1
bspc config window_gap          5
bspc config split_ratio         0.51
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# ===== Window rules =====
bspc rule -a Firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
